---
version: 2

jobs:
  build:
    machine: true

    steps:
      - checkout

      - run:
          name: execute hello world
          command: |
            pip install pipenv
            pipenv sync
            cd my-new-role
            pipenv run molecule test
