---
version: 2

jobs:
  hello_world_job:
    docker:
      - image: circleci/python:3.7.2

    steps:
      - checkout

      - run:
          name: execute hello world
          command: |
            echo 'hello world'
