---
version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7.2

    steps:
      - checkout

      - run:
          name: execute hello world
          command: |
            pip install pipenv
            pipenv install
            cd my-new-role
            pipenv run molecule test
